# Generated by Django 4.0.4 on 2022-05-22 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_student_level_student_mobnum_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
