# Generated by Django 4.0.4 on 2022-05-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0005_student_active_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
