# Generated by Django 4.0.4 on 2022-05-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0006_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
