# Generated by Django 4.0.4 on 2022-05-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0007_student_complaint_alter_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('stuID', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='complaint',
        ),
    ]
